# Generated by Django 5.1.1 on 2024-12-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='intereses',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='metas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nivel_experiencia',
            field=models.CharField(blank=True, choices=[('Principiante', 'Principiante'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=15),
        ),
    ]
