# Generated by Django 5.1.1 on 2024-12-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0002_perfilusuario_edad_perfilusuario_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
