# Generated by Django 5.1.1 on 2024-12-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0003_perfilusuario_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='aprobado_por_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='es_entrenador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='especialidades',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='experiencia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='formacion',
            field=models.TextField(blank=True),
        ),
    ]
