# Generated by Django 5.1.1 on 2024-12-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0004_perfilusuario_aprobado_por_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='aprobado_por_admin',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='es_entrenador',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='especialidades',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='experiencia',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='formacion',
        ),
    ]
