# Generated by Django 5.1.1 on 2024-12-27 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0005_remove_perfilusuario_aprobado_por_admin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidades', models.TextField(blank=True, verbose_name='Especialidades deportivas')),
                ('experiencia', models.TextField(blank=True, verbose_name='Experiencia profesional')),
                ('formacion', models.TextField(blank=True, verbose_name='Formación académica')),
                ('aprobado_por_admin', models.BooleanField(default=False, verbose_name='Aprobado por el administrador')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
