# Generated by Django 5.1.1 on 2024-12-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0006_entrenador'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='plazas_abiertas',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
