# Generated by Django 5.1.1 on 2024-12-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0007_entrenador_plazas_abiertas'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='es_entrenador',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
