# Generated by Django 5.1.1 on 2025-01-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0013_actividad_chatactividad_mensajeactividad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='imagen',
            field=models.ImageField(default='default_actividad.jpg', upload_to='actividades/'),
        ),
    ]
