# Generated by Django 5.1.1 on 2025-01-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0014_actividad_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='imagen',
            field=models.ImageField(default='imgs/default_actividad.jpg', upload_to='actividades/'),
        ),
    ]
