# Generated by Django 5.1.1 on 2025-01-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0015_alter_actividad_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='duracion',
        ),
        migrations.AddField(
            model_name='actividad',
            name='duracion_unidad',
            field=models.CharField(choices=[('seconds', 'Segundos'), ('minutes', 'Minutos'), ('hours', 'Horas')], default='minutes', max_length=10),
        ),
        migrations.AddField(
            model_name='actividad',
            name='duracion_valor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
