# Generated by Django 5.1.1 on 2025-01-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0017_mensajeprivado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeactividad',
            name='editado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensajegrupo',
            name='editado',
            field=models.BooleanField(default=False),
        ),
    ]
