# Generated by Django 5.1.1 on 2025-01-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0018_mensajeactividad_editado_mensajegrupo_editado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeprivado',
            name='editado',
            field=models.BooleanField(default=False),
        ),
    ]
