# Generated by Django 5.1.1 on 2025-01-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0019_mensajeprivado_editado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeactividad',
            name='leido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensajegrupo',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
