# Generated by Django 5.1.1 on 2025-01-04 18:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0021_grupovisitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupovisitado',
            name='ultima_visita',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
