# Generated by Django 5.1.1 on 2025-01-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0023_publicacion_comentario_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
