# Generated by Django 5.1.1 on 2025-01-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0024_publicacion_destacado'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudEntrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10, verbose_name='Género')),
                ('nivel_experiencia', models.CharField(choices=[('Principiante', 'Principiante'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=15, verbose_name='Nivel de Experiencia')),
                ('especialidades', models.TextField(verbose_name='Especialidades deportivas')),
                ('experiencia', models.TextField(verbose_name='Experiencia profesional')),
                ('formacion', models.TextField(verbose_name='Formación académica')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
            ],
        ),
    ]
