# Generated by Django 5.1.1 on 2025-01-10 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0025_solicitudentrenador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('distancia_objetivo', models.FloatField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='retos/')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacionReto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia_acumulada', models.FloatField(default=0)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='skylimit.reto')),
            ],
            options={
                'unique_together': {('usuario', 'reto')},
            },
        ),
    ]
