# Generated by Django 5.1.1 on 2025-01-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0026_reto_participacionreto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participacionreto',
            old_name='distancia_acumulada',
            new_name='progreso_acumulado',
        ),
        migrations.RenameField(
            model_name='reto',
            old_name='distancia_objetivo',
            new_name='objetivo',
        ),
        migrations.AddField(
            model_name='reto',
            name='unidad_objetivo',
            field=models.CharField(choices=[('km', 'Kilómetros'), ('m', 'Metros'), ('s', 'Segundos'), ('min', 'Minutos'), ('rep', 'Repeticiones')], default='km', max_length=20),
        ),
    ]
