# Generated by Django 5.1.1 on 2025-01-10 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0027_rename_distancia_acumulada_participacionreto_progreso_acumulado_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participacionreto',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='participacionreto',
            name='unidad',
            field=models.CharField(default='kilómetros', max_length=20),
        ),
        migrations.AlterField(
            model_name='participacionreto',
            name='reto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skylimit.reto'),
        ),
    ]
