# Generated by Django 5.1.1 on 2025-01-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0028_alter_participacionreto_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacionreto',
            name='progreso_acumulado',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reto',
            name='objetivo',
            field=models.PositiveIntegerField(),
        ),
    ]
