# Generated by Django 5.1.1 on 2025-01-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0029_alter_participacionreto_progreso_acumulado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reto',
            name='unidad_objetivo',
            field=models.CharField(choices=[('km', 'Kilómetros'), ('pasos', 'Pasos'), ('horas', 'Horas'), ('min', 'Minutos'), ('rep', 'Repeticiones')], default='km', max_length=20),
        ),
    ]
