# Generated by Django 5.1.1 on 2025-01-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0032_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='entrenadores/avatars/', verbose_name='Avatar'),
        ),
    ]
