# Generated by Django 5.1.1 on 2025-01-11 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0033_entrenador_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrenador',
            name='avatar',
        ),
    ]
