# Generated by Django 5.1.1 on 2025-01-23 17:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0035_entrenador_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('objetivo', models.FloatField()),
                ('unidad', models.CharField(choices=[('kg', 'Kilogramos'), ('km', 'Kilómetros'), ('pasos', 'Pasos'), ('horas', 'Horas'), ('minutos', 'Minutos'), ('repeticiones', 'Repeticiones')], max_length=20)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField()),
                ('completada', models.BooleanField(default=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='metas/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('cantidad', models.FloatField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='progreso/')),
                ('video', models.FileField(blank=True, null=True, upload_to='progreso/videos/')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='skylimit.metausuario')),
            ],
        ),
    ]
