# Generated by Django 5.1.1 on 2025-01-24 18:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0037_logro_logrousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metausuario',
            name='fecha_fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='metausuario',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
