# Generated by Django 5.1.1 on 2025-01-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0038_alter_metausuario_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metausuario',
            name='correo_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
