# Generated by Django 5.1.1 on 2025-01-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0039_metausuario_correo_enviado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metausuario',
            name='imagen',
            field=models.ImageField(blank=True, default='metas/default-reto.png', null=True, upload_to='metas/'),
        ),
    ]
