# Generated by Django 5.1.1 on 2025-01-25 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0040_alter_metausuario_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='logrousuario',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='logrousuario',
            name='meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logros', to='skylimit.metausuario'),
        ),
        migrations.AlterUniqueTogether(
            name='logrousuario',
            unique_together={('usuario', 'logro', 'meta')},
        ),
    ]
