# Generated by Django 5.1.1 on 2025-01-25 11:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0041_alter_logrousuario_unique_together_logrousuario_meta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresometa',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
