# Generated by Django 5.1.1 on 2025-01-25 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0042_alter_progresometa_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logrousuario',
            name='logro',
        ),
        migrations.AlterUniqueTogether(
            name='logrousuario',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='logrousuario',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='logrousuario',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Logro',
        ),
        migrations.DeleteModel(
            name='LogroUsuario',
        ),
    ]
