# Generated by Django 5.1.1 on 2025-01-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0043_remove_logrousuario_logro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metausuario',
            name='completada',
        ),
        migrations.RemoveField(
            model_name='metausuario',
            name='correo_enviado',
        ),
    ]
