# Generated by Django 5.1.1 on 2025-01-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0045_solicitudentrenamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudentrenamiento',
            name='respuesta_recibida',
            field=models.BooleanField(default=False),
        ),
    ]
