# Generated by Django 5.1.1 on 2025-01-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0047_entrenamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parte_cuerpo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ejercicios/imagenes/')),
                ('video', models.FileField(blank=True, null=True, upload_to='ejercicios/videos/')),
            ],
        ),
    ]
