# Generated by Django 5.1.1 on 2025-01-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skylimit', '0048_entreno'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreno',
            name='descripcionEjer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
